import type { Metadata } from "next";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper";
import { ToastProvider } from "./components/providers/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= "antialiased"
      >

        <ToastProvider>
        <LayoutWrapper>
          {children}
        </LayoutWrapper>
        </ToastProvider>
      </body>
    </html>
  );
}
